version: '3'

services:
  mt5:
    build: .
    container_name: mt5
    #volumes:
    #  - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    environment:
      - CUSTOM_USER=tuhin
      - PASSWORD=tuhin
